### ISSUE TITLE
An Error

### ISSUE THREAD

**Issue by smartnavdeep** [Ved-programmer/Numerical-Base-Converter#1]
Hi Ved, happy to see that you created a new repo,
I was testing it and wanted to see that are there any error or not
When we give a string, this is happening....
![Screenshot 2020-10-22 184534](https://user-images.githubusercontent.com/65970997/96877336-20552400-1497-11eb-82ce-516d04b6cc3d.png)

Well this is a normal bug which can be fixed with a simple try and except method.

Thank you
Regards,
Navdeep

**Comment by Ved-programmer** [comment]
thanks, will fix it surely
